import { Link, useNavigate } from "react-router-dom"
import { ArrowRight, ChevronRight, CreditCard, MapPin, Package, ShieldCheck, UserRound } from "lucide-react"
import { useAuth } from "../context/StoreContext"

export default function AccountPage() {
  const { user, logout } = useAuth()
  const navigate = useNavigate()
  const signOut = () => { logout(); navigate("/") }
  return <div className="account-page"><div className="container"><div className="account-heading"><div><span className="section-eyebrow">Your account</span><h1>Hello, {user?.name?.split(" ")[0]}</h1><p>Manage your orders, addresses, and shopping preferences.</p></div><button type="button" className="secondary-button" onClick={signOut}>Sign out</button></div><div className="account-grid"><Link className="account-tile" to="/account/orders"><Package size={24} /><strong>Your Orders</strong><span>Track, return, or buy again</span><ChevronRight size={17} /></Link><Link className="account-tile" to="/account"><MapPin size={24} /><strong>Your Addresses</strong><span>Manage delivery addresses</span><ChevronRight size={17} /></Link><Link className="account-tile" to="/account"><ShieldCheck size={24} /><strong>Login & Security</strong><span>Password and privacy settings</span><ChevronRight size={17} /></Link><Link className="account-tile" to="/checkout"><CreditCard size={24} /><strong>Payment & Checkout</strong><span>Review your checkout options</span><ChevronRight size={17} /></Link></div><section className="account-details"><div className="account-details__heading"><UserRound size={22} /><div><h2>Account details</h2><p>Your account information</p></div></div><div className="account-details__grid"><div><span>Name</span><strong>{user?.name}</strong></div><div><span>Email</span><strong>{user?.email}</strong></div><div><span>Member since</span><strong>Today</strong></div></div></section><section className="account-callout"><div><span className="section-eyebrow">Need a hand?</span><h2>We're here to help</h2><p>Find answers, track a package, or get support from Customer Service.</p></div><Link className="secondary-button" to="/account">Visit help center <ArrowRight size={17} /></Link></section></div></div>
}
