import { useEffect, useState } from "react"
import { Check, Eye, EyeOff, Search, Trash2 } from "lucide-react"
import { adminApi, errorMessage } from "../services/api"
import { AdminEmpty, AdminError, AdminModal, AdminPageHeader, AdminPagination, AdminStatusBadge, AdminTable, AdminToast } from "../components/admin/AdminUI"

const payloadOf = (result) => result?.data?.data || result?.data || result || {}

export default function AdminReviewsPage() {
  const [query, setQuery] = useState({ search: "", rating: "", status: "all", sort: "newest", page: 1, limit: 20 })
  const [result, setResult] = useState({ rows: [], meta: {} })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [modal, setModal] = useState(null)
  const [toast, setToast] = useState("")
  const load = () => { setLoading(true); adminApi.reviews.list(query).then((response) => { const value = payloadOf(response); setResult({ rows: Array.isArray(value) ? value : value.data || [], meta: response.meta || response.data?.meta || {} }) }).catch((requestError) => setError(errorMessage(requestError, "Reviews could not be loaded."))).finally(() => setLoading(false)) }
  useEffect(load, [query.search, query.rating, query.status, query.sort, query.page])
  const moderate = async (status) => { try { await adminApi.reviews.moderate(modal.id, status); setModal(null); setToast(`Review ${status === "approved" ? "approved" : "hidden"}.`); load() } catch (requestError) { setError(errorMessage(requestError, "Review could not be updated.")) } }
  const remove = async () => { try { await adminApi.reviews.remove(modal.id); setModal(null); setToast("Review deleted."); load() } catch (requestError) { setError(errorMessage(requestError, "Review could not be deleted.")) } }
  const sortMap = { rating: { asc: "lowest", desc: "highest" }, date: { asc: "oldest", desc: "newest" } }
  const activeSort = Object.entries(sortMap).find(([, directions]) => Object.values(directions).includes(query.sort)) || []
  const handleSort = (key) => {
    const directions = sortMap[key]
    if (!directions) return
    setQuery({ ...query, sort: query.sort === directions.asc ? directions.desc : directions.asc, page: 1 })
  }
  const columns = [{ key: "customer", label: "Customer", render: (row) => <div className="admin-product-name"><strong>{row.user?.name || row.userName || "Customer"}</strong><small>{row.user?.email || "—"}</small></div> }, { key: "product", label: "Product", render: (row) => row.product?.title || row.productTitle || "—" }, { key: "rating", label: "Rating", sortable: true, render: (row) => `${row.rating} / 5` }, { key: "comment", label: "Review", render: (row) => <div className="admin-review-copy"><strong>{row.title}</strong><span>{row.comment}</span></div> }, { key: "date", label: "Date", sortable: true, render: (row) => row.createdAt ? new Date(row.createdAt).toLocaleDateString() : "—" }, { key: "status", label: "Status", render: (row) => <AdminStatusBadge value={row.status || "approved"} /> }, { key: "actions", label: "Actions", render: (row) => <div className="admin-row-actions"><button type="button" onClick={() => setModal({ review: row, action: "approve" })} aria-label="Approve review"><Check size={15} /></button><button type="button" onClick={() => setModal({ review: row, action: "hide" })} aria-label="Hide review"><EyeOff size={15} /></button><button type="button" onClick={() => setModal({ review: row, action: "delete" })} aria-label="Delete review"><Trash2 size={15} /></button></div> }]
  return <div className="admin-page"><AdminPageHeader eyebrow="Content management" title="Reviews" description="Moderate customer feedback without removing valid customer history." /><AdminToast message={toast} onClose={() => setToast("")} />{error && <AdminError message={error} onRetry={load} />}<div className="admin-toolbar"><div className="admin-search-field"><Search size={16} /><input value={query.search} onChange={(event) => setQuery({ ...query, search: event.target.value, page: 1 })} placeholder="Search review, product, customer…" aria-label="Search reviews" /></div><select value={query.rating} onChange={(event) => setQuery({ ...query, rating: event.target.value, page: 1 })} aria-label="Filter review rating"><option value="">All ratings</option>{[5, 4, 3, 2, 1].map((value) => <option value={value} key={value}>{value} stars</option>)}</select><select value={query.status} onChange={(event) => setQuery({ ...query, status: event.target.value, page: 1 })} aria-label="Filter review status"><option value="all">All statuses</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="hidden">Hidden</option></select></div><AdminTable columns={columns} rows={result.rows} loading={loading} sortKey={activeSort[0]} sortDirection={activeSort[1] === Object.values(sortMap[activeSort[0]] || {})[1] ? "desc" : "asc"} onSort={handleSort} empty={<AdminEmpty title="No reviews found" message="Moderation filters will appear here." />} /><div className="admin-table-footer"><span>{result.meta.total || 0} reviews</span><AdminPagination page={result.meta.page || query.page} pages={result.meta.pages || 1} onPage={(page) => setQuery({ ...query, page })} /></div><AdminModal open={Boolean(modal)} title={modal?.action === "delete" ? "Delete review" : `${modal?.action === "approve" ? "Approve" : "Hide"} review`} onClose={() => setModal(null)} footer={<><button className="admin-secondary-button" type="button" onClick={() => setModal(null)}>Cancel</button><button className={modal?.action === "delete" ? "admin-danger-button" : "admin-primary-button"} type="button" onClick={() => modal?.action === "delete" ? remove() : moderate(modal.action)}>Confirm</button></>}><p>{modal?.review?.title || "This action changes what customers can see."}</p></AdminModal></div>
}
