import { useEffect, useState } from "react"
import { Link } from "react-router-dom"
import { Eye, RefreshCw, Search } from "lucide-react"
import { adminApi, errorMessage } from "../services/api"
import { AdminEmpty, AdminError, AdminLoading, AdminPageHeader, AdminPagination, AdminStatusBadge, AdminTable } from "../components/admin/AdminUI"

const payloadOf = (result) => result?.data?.data || result?.data || result || {}
const money = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value || 0))

export default function AdminOrdersPage() {
  const [query, setQuery] = useState({ search: "", status: "all", sort: "newest", page: 1, limit: 20 })
  const [result, setResult] = useState({ rows: [], meta: {} })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const load = () => { setLoading(true); setError(""); adminApi.orders.list(query).then((response) => { const value = payloadOf(response); setResult({ rows: Array.isArray(value) ? value : value.data || [], meta: response.meta || response.data?.meta || {} }) }).catch((requestError) => setError(errorMessage(requestError, "We couldn't load orders."))).finally(() => setLoading(false)) }
  useEffect(load, [query.search, query.status, query.sort, query.page])
  const columns = [{ key: "orderNumber", label: "Order", render: (row) => <Link className="admin-order-link" to={`/admin/orders/${row.id}`}><strong>{row.orderNumber || row.id}</strong><small>{row.createdAt ? new Date(row.createdAt).toLocaleDateString() : "—"}</small></Link> }, { key: "customer", label: "Customer", render: (row) => <div className="admin-product-name"><strong>{row.customer?.name || row.user?.name || "Customer"}</strong><small>{row.customer?.email || row.user?.email || "—"}</small></div> }, { key: "items", label: "Items", render: (row) => row.itemCount ?? row.items?.length ?? 0 }, { key: "total", label: "Total", render: (row) => <strong>{money(row.total)}</strong> }, { key: "payment", label: "Payment", render: (row) => row.paymentStatus || "Paid" }, { key: "status", label: "Status", render: (row) => <AdminStatusBadge value={row.status} /> }, { key: "actions", label: "Actions", render: (row) => <Link className="admin-icon-button" to={`/admin/orders/${row.id}`} aria-label={`View order ${row.orderNumber || row.id}`}><Eye size={16} /></Link> }]
  return <div className="admin-page"><AdminPageHeader eyebrow="Order operations" title="Orders" description="Search, sort, and move customer orders through the fulfillment timeline." actions={<button className="admin-secondary-button" type="button" onClick={load}><RefreshCw size={15} /> Refresh</button>} />{error && <AdminError message={error} onRetry={load} />}<div className="admin-toolbar"><div className="admin-search-field"><Search size={16} /><input value={query.search} onChange={(event) => setQuery({ ...query, search: event.target.value, page: 1 })} placeholder="Search order ID, customer, email…" aria-label="Search orders" /></div><select value={query.status} onChange={(event) => setQuery({ ...query, status: event.target.value, page: 1 })} aria-label="Filter orders"><option value="all">All statuses</option>{["Pending", "Processing", "Shipped", "Out for delivery", "Delivered", "Cancelled"].map((value) => <option key={value}>{value}</option>)}</select><select value={query.sort} onChange={(event) => setQuery({ ...query, sort: event.target.value, page: 1 })} aria-label="Sort orders"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest total</option><option value="lowest">Lowest total</option></select></div><AdminTable columns={columns} rows={result.rows} loading={loading} empty={<AdminEmpty title="No orders found" message="Try changing the order filters." />} /><div className="admin-table-footer"><span>{result.meta.total || 0} orders</span><AdminPagination page={result.meta.page || query.page} pages={result.meta.pages || 1} onPage={(page) => setQuery({ ...query, page })} /></div></div>
}
