import { useEffect, useState } from "react"
import { Edit3, Plus, RefreshCw, Search, Trash2 } from "lucide-react"
import { adminApi, errorMessage } from "../services/api"
import { AdminEmpty, AdminError, AdminLoading, AdminModal, AdminPageHeader, AdminStatusBadge, AdminTable, AdminToast } from "../components/admin/AdminUI"

const payloadOf = (result) => result?.data?.data || result?.data || result || {}
const blank = { name: "", slug: "", description: "", active: true }

export default function AdminCatalogPage({ kind }) {
  const config = kind === "brand" ? { title: "Brands", singular: "brand", endpoint: adminApi.brands, icon: "brand" } : { title: "Categories", singular: "category", endpoint: adminApi.categories, icon: "category" }
  const [rows, setRows] = useState([])
  const [search, setSearch] = useState("")
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [form, setForm] = useState(null)
  const [modal, setModal] = useState(null)
  const [toast, setToast] = useState("")
  const load = () => { setLoading(true); setError(""); config.endpoint.list({ search, limit: 100 }).then((result) => { const value = payloadOf(result); setRows(Array.isArray(value) ? value : value.data || []) }).catch((requestError) => setError(errorMessage(requestError, `We couldn't load ${config.title.toLowerCase()}.`))).finally(() => setLoading(false)) }
  useEffect(load, [search])
  const save = async (event) => { event.preventDefault(); try { if (form.id) await config.endpoint.update(form.id, form); else await config.endpoint.create(form); setForm(null); setToast(`${config.singular[0].toUpperCase()}${config.singular.slice(1)} saved.`); load() } catch (requestError) { setError(errorMessage(requestError, `${config.singular} could not be saved.`)) } }
  const remove = async () => { try { await config.endpoint.remove(modal.id); setModal(null); setToast(`${config.singular[0].toUpperCase()}${config.singular.slice(1)} deleted.`); load() } catch (requestError) { setError(errorMessage(requestError, `${config.singular} could not be deleted.`)) } }
  const columns = [{ key: "name", label: config.title.slice(0, -1), render: (row) => <strong>{row.name}</strong> }, { key: "description", label: "Description", render: (row) => row.description || "—" }, { key: "productCount", label: "Products", render: (row) => row.productCount ?? row.productsCount ?? 0 }, { key: "status", label: "Status", render: (row) => <AdminStatusBadge value={row.active === false ? "Inactive" : "Active"} /> }, { key: "createdAt", label: "Created", render: (row) => row.createdAt ? new Date(row.createdAt).toLocaleDateString() : "—" }, { key: "actions", label: "Actions", render: (row) => <div className="admin-row-actions"><button type="button" onClick={() => setForm({ ...blank, ...row })} aria-label={`Edit ${row.name}`}><Edit3 size={15} /></button><button type="button" onClick={() => setModal(row)} aria-label={`Delete ${row.name}`}><Trash2 size={15} /></button></div> }]
  return <div className="admin-page"><AdminPageHeader eyebrow="Catalog taxonomy" title={config.title} description={`Create and maintain the ${config.title.toLowerCase()} used by customer search and navigation.`} actions={<><button className="admin-secondary-button" type="button" onClick={load}><RefreshCw size={15} /> Refresh</button><button className="admin-primary-button" type="button" onClick={() => setForm({ ...blank })}><Plus size={16} /> Add {config.singular}</button></>} /><AdminToast message={toast} onClose={() => setToast("")} />{error && <AdminError message={error} onRetry={load} />}<div className="admin-toolbar"><div className="admin-search-field"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${config.title.toLowerCase()}…`} aria-label={`Search ${config.title}`} /></div></div><AdminTable columns={columns} rows={rows} loading={loading} empty={<AdminEmpty title={`No ${config.title.toLowerCase()} found`} message="Create the first taxonomy entry to organize your catalog." />} />{form && <AdminModal open title={`${form.id ? "Edit" : "Add"} ${config.singular}`} onClose={() => setForm(null)} footer={<><button className="admin-secondary-button" type="button" onClick={() => setForm(null)}>Cancel</button><button className="admin-primary-button" type="submit" form="admin-catalog-form">Save</button></>}><form id="admin-catalog-form" className="admin-form-stack" onSubmit={save}><label className="admin-field">Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label className="admin-field">Slug<input value={form.slug || ""} onChange={(event) => setForm({ ...form, slug: event.target.value })} placeholder="Generated if blank" /></label><label className="admin-field">Description<textarea rows={3} value={form.description || ""} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="admin-check-label"><input type="checkbox" checked={form.active !== false} onChange={(event) => setForm({ ...form, active: event.target.checked })} /> Active</label></form></AdminModal>}{modal && <AdminModal open title={`Delete ${config.singular}`} onClose={() => setModal(null)} footer={<><button className="admin-secondary-button" type="button" onClick={() => setModal(null)}>Cancel</button><button className="admin-danger-button" type="button" onClick={remove}>Delete</button></>}><p>Delete <strong>{modal.name}</strong>? Entries used by products cannot be deleted.</p></AdminModal>}</div>
}
