import { Link } from "react-router-dom"
import { Scale, Trash2 } from "lucide-react"
import { useShoppingMemory } from "../context/StoreContext"
import { money } from "../utils/format"
import { usePageMeta } from "../utils/seo"

export default function ComparePage() {
  const { compare, toggleCompare, clearCompare } = useShoppingMemory()
  usePageMeta("Compare Products", "Compare product details side by side.")
  return <div className="compare-page"><div className="container"><div className="breadcrumbs"><Link to="/">Home</Link><span>›</span><strong>Compare Products</strong></div><div className="page-title-row"><div><h1>Compare products</h1><p>Review up to four products side by side.</p></div>{compare.length > 0 && <button className="secondary-button" type="button" onClick={clearCompare}><Trash2 size={16} /> Clear comparison</button>}</div>{compare.length === 0 ? <div className="empty-state"><Scale size={45} /><h2>Nothing to compare yet</h2><p>Use the Compare button on product cards to build a table.</p><Link className="primary-button" to="/search">Browse products</Link></div> : <div className="comparison-wrap"><table className="comparison-table"><thead><tr><th>Product</th>{compare.map((product) => <th key={product.id}><Link to={`/product/${product.id}`}><img src={product.images?.[0]} alt={product.title} /></Link><Link to={`/product/${product.id}`}>{product.title}</Link><button type="button" className="delete-link" onClick={() => toggleCompare(product)}><Trash2 size={13} /> Remove</button></th>)}</tr></thead><tbody><tr><th>Price</th>{compare.map((product) => <td key={product.id}>{money(product.price)}{product.originalPrice > product.price && <small>{money(product.originalPrice)}</small>}</td>)}</tr><tr><th>Rating</th>{compare.map((product) => <td key={product.id}>{product.rating} / 5 <small>{product.reviewCount?.toLocaleString()} ratings</small></td>)}</tr><tr><th>Brand</th>{compare.map((product) => <td key={product.id}>{product.brand}</td>)}</tr><tr><th>Category</th>{compare.map((product) => <td key={product.id}>{product.category}</td>)}</tr><tr><th>Availability</th>{compare.map((product) => <td key={product.id}>{product.stock > 0 ? <span className="in-stock-text">In stock</span> : <span className="out-stock-text">Out of stock</span>}</td>)}</tr><tr><th>Discount</th>{compare.map((product) => <td key={product.id}>{product.discount || 0}% off</td>)}</tr><tr><th>Delivery</th>{compare.map((product) => <td key={product.id}>{product.delivery || "Standard delivery"}</td>)}</tr><tr><th>Key features</th>{compare.map((product) => <td key={product.id}><ul>{(product.features || []).slice(0, 4).map((feature) => <li key={feature}>{feature}</li>)}</ul></td>)}</tr></tbody></table></div>}</div></div>
}
